spring.application.name=marieeanne
chave.secreta=lcBtO9ny4z7PwCNStO4NVl56cs4JAcyITL4qWvkjidVU7oKfJ1qfBjBWOjZVikIbRzwiFxYx2Yucdf0YumZbWS
api.security.refresh.expiration-days=7
api.mercadopago.acess.token=TEST-4795265138205761-060119-455c347028ea58a21f90311d27e29ccc-3442147681
spring.datasource.url=jdbc:postgresql://localhost:5432/marieanne
spring.datasource.username=admin-marieanne
spring.datasource.password=spring
upload.directory=uploads/produtos
spring.datasource.driver-class-name=org.postgresql.Driver
payment.mercadopago.webhook-secret=fsnnbln
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
api.security.refresh.expiration-days=7
spring.jpa.open-in-view=false
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


#ambiente de teste de envio de email via mailtrap

spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=aa7ab9001@smtp-brevo.com
spring.mail.password=xsmtpsib-b19fd5b5933f9273d8281682c94d95e6b804b2c34e332d68b2c78309ded47567-jPI7IhwohhQX3BZz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


mercadopago.webhook.secret=6e6b2181b5dd174fa221ae6440e69f6870ddef93e196f1b080852169c00c1834